review:
  - paths:
      - cmd/*
      - api/*
      - controllers/*
      - internal/*
      - core/*
    reviewers:
      - spolti
      - davidesalerno
  - paths:
      - test/*
    reviewers:
      - radtriste
  - paths:
      - Jenkinsfile*
      - .ci
      - .github
    reviewers:
      - radtriste
defaultReviewers:
  - spolti
  - davidesalerno
