name: hello-world
on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"